#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
#yabai -m config window_border on 
#yabai -m config window_border_width 6
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
# NOTE: for OBS floating head
# yabai -m config left_padding 450
yabai -m config right_padding 15
yabai -m config window_gap 15

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^HazeOver$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Middle$" manage=off
yabai -m rule --add app="^AltTab$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^BetterDisplay$" manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Keychron Engine$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^OBS Studio$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^SF Symbols" manage=off

#configure height of sketchybar
yabai -m config external_bar all:32:0

echo "yabai configuration loaded.."

#add janky borders
borders active_color=0xff8948ff inactive_color=0x00ffffff width=12.0 &
