If:
  PathMatch: '.*\.c$'
CompileFlags:
  Compiler: /Users/faustozamparelli/.local/toolchains/bin/gcc
---
If:
  PathMatch: '.*\.(cc|cpp|cxx|c\+\+|hh|hpp|hxx|h\+\+)$'
CompileFlags:
  Compiler: /Users/faustozamparelli/.local/toolchains/bin/g++
