#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=42 \
                 blur_radius=30 \
                 position=top \
                 sticky=off \
                 padding_left=8 \
                 padding_right=8 \
                 color=$BAR_BG

ICON_FONT="Iosevka NFM:Regular:24.0"
LABEL_FONT=".SF NS:Medium:14.0"
LABEL_FONT_BOLD=".SF NS:Semibold:14.0"

export ICON_FONT LABEL_FONT LABEL_FONT_BOLD

sketchybar --default icon.font="$ICON_FONT" \
                     icon.color=$TEXT \
                     label.font="$LABEL_FONT" \
                     label.color=$TEXT \
                     background.color=$ITEM_BG \
                     background.corner_radius=9 \
                     background.height=34 \
                     background.border_color=$ACCENT_DARK \
                     background.border_width=1 \
                     padding_left=4 \
                     padding_right=4 \
                     icon.padding_left=7 \
                     icon.padding_right=4 \
                     label.padding_left=2 \
                     label.padding_right=7

source "$ITEM_DIR/left/workspaces.sh"
source "$ITEM_DIR/left/front_app.sh"

source "$ITEM_DIR/center/media.sh"
source "$ITEM_DIR/right/status.sh"

"$PLUGIN_DIR/aerospace/poller.sh" &

sketchybar --update
